server:
  port: 8001
  
## mybatis配置
mybatis:
  config-location: classpath:mybatis/config/mybatis.cfg.xml
  type-aliases-package: com.xywei.entity
  mapper-locations:
  - classpath:mybatis/mapper/**/*.xml 
  

## 服务名/数据库/数据源配置
spring: 
  application:
    name: provider-dept-8001 #与server.context-path有什么区别
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/xy-spring-cloud-first
    username: root
    password: xieSHI123321
    dbcp2:
      initial-size: 5 # 初始化连接数
      min-idle: 5 # 维持最小连接数
      max-total: 5 # 最大连接数
      max-wait-millis: 1000 # 等待时间
    