server:
  port: 8002
  
## mybatis配置
mybatis:
  config-location: classpath:mybatis/config/mybatis.cfg.xml
  type-aliases-package: com.xywei.entity
  mapper-locations:
  - classpath:mybatis/mapper/**/*.xml 
  

## 服务名/数据库/数据源配置
spring: 
  application:
    name: provider-dept-service #eurakla中对外暴露的微服务名字， 与server.context-path有什么区别
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/xy-spring-cloud-first-8002
    username: root
    password: xieSHI123321
    dbcp2:
      initial-size: 5 # 初始化连接数
      min-idle: 5 # 维持最小连接数
      max-total: 5 # 最大连接数
      max-wait-millis: 1000 # 等待时间

eureka:
  client:
    service-url: 
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
  instance:
    instance-id: provider-dept-8002
    prefer-ip-address: true
    
info:
  app.name: $project.build.finalName$
  build.version: $project.version$