server:
  port: 8004
  
  

## 服务名/数据库/数据源配置
spring: 
  application:
    name: provider-dept-service #eurakla中对外暴露的微服务名字， 与server.context-path有什么区别
 
info:
  app.name: $project.build.finalName$
  build.version: $project.version$